# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models

def populate_expires_date(apps, schema_editor):
    """
    Popula o campo data de expiração das perguntas já existentes colocando um mẽs de validade para cada.
    """
    from datetime import timedelta

    db_alias = schema_editor.connection.alias
    Question = apps.get_model('polls', 'Question')

    for row in Question.objects.using(db_alias).filter(expires_date__isnull=True):
        row.expires_date = row.pub_date + timedelta(days=30)
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170429_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expires_date',
            field=models.DateTimeField(null=True, verbose_name='expires at'),
        ),
        migrations.RunPython(populate_expires_date, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='expires_date',
            field=models.DateTimeField(verbose_name='expires at'),
        )
    ]
